---
- name: Configuração do host cliente CLI
  hosts: cli
  become: yes
  vars:
    nfs_server: 192.168.56.102
    nfs_origem: "/dados/nfs"
    nfs_destino: "/var/nfs"

  tasks:
    - name: Instalar pacotes gráficos e NFS
      apt:
        name:
          - firefox-esr
          - xauth
          - autofs
          - nfs-common
        state: present
        update_cache: yes

    - name: Habilitar X11 forwarding no SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^X11Forwarding'
        line: 'X11Forwarding yes'

    - name: Reiniciar serviço SSH
      service:
        name: ssh
        state: restarted

    - name: Criar diretório para NFS
      file:
        path: "{{ nfs_destino }}"
        state: directory

    - name: Configurar auto.master
      copy:
        dest: /etc/auto.master.d/nfs.autofs
        content: |
          {{ nfs_destino }} /etc/auto.nfs

    - name: Configurar auto.nfs
      copy:
        dest: /etc/auto.nfs
        content: |
          nfs -rw,sync {{ nfs_server }}:{{ nfs_origem }}

    - name: Reiniciar autofs
      service:
        name: autofs
        state: restarted
        enabled: yes

